
//DATABASE CONSTANTS
const MY_SQL_HOST ='localhost';
const MY_SQL_USERNAME = 'kr34t1v';
const MY_SQL_PASSWORD = 'Papenvleis1!';
const DATABASE_NAME = 'matcha';
const USERS_TABLE = 'Users'
const USERS_TABLE_COLUMNS = `
Id INT AUTO_INCREMENT PRIMARY KEY,
Username VARCHAR(255) NOT NULL,
Firstname VARCHAR(255) NOT NULL,
Lastname VARCHAR(255) NOT NULL,
Birthdate DATE NOT NULL,
Gender VARCHAR(255) NOT NULL,
SexualPreference VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL,
NewEmail VARCHAR(255),
Password VARCHAR(255) NOT NULL,
Biography VARCHAR(255),
Interests JSON,
Images JSON,
VerifyKey VARCHAR(255),
DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DateVerified DATE,
DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DateDeleted DATE
`;

module.exports = {
	MY_SQL_HOST,
	MY_SQL_USERNAME,
	MY_SQL_PASSWORD,
	DATABASE_NAME,
	USERS_TABLE,
	USERS_TABLE_COLUMNS
}