//DATABASE CONSTANTS
const MY_SQL_HOST ='localhost';
const MY_SQL_USERNAME = 'kr34t1v';
const MY_SQL_PASSWORD = 'Papenvleis1!';
const DATABASE_NAME = 'matcha';
const USERS_TABLE = `${DATABASE_NAME}.Users`;
const USERS_TABLE_COLUMNS = `
Id INT AUTO_INCREMENT PRIMARY KEY,
AccessToken NVARCHAR(255),
AccessTime DATETIME,
Username NVARCHAR(255) NOT NULL,
Firstname NVARCHAR(255) NOT NULL,
Lastname NVARCHAR(255) NOT NULL,
Birthdate DATE NOT NULL,
Gender NVARCHAR(255) NOT NULL,
SexualPreference NVARCHAR(255) NOT NULL,
Email NVARCHAR(255),
NewEmail NVARCHAR(255),
DateVerified DATE,
VerifyKey NVARCHAR(255),
Password NVARCHAR(255) NOT NULL,
Biography NVARCHAR(255),
Interests JSON,
Location JSON,
Avatar NVARCHAR(255),
Images JSON,
BlockedUsers JSON,
ViewedBy JSON,
LikedBy JSON,
Liked JSON,
DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
DateDeleted DATETIME
`;
const CHAT_TABLE = `${DATABASE_NAME}.Chats`;
const CHAT_TABLE_COLUMNS = `
FromId INT NOT NULL,
ToId INT NOT NULL,
Message NVARCHAR(1000) NOT NULL,
Viewed BOOLEAN,
TimeStamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
`;

const UPLOAD_PATH = __dirname + '/Uploads';
const CLOUDINARY_CONNECTION = {
	cloudName: 'asdjfup-vqq1',
	api_key: '439656192988452',
	api_secret: 'upQlu1NcoKeXGluWQARX9qwL8mo'
}
const IMAGE_FILTER = /\.(jpg|jpeg|png|gif)$/;

//SECURITY REQUIREMENTS
const PASSWORD_LENGTH = 8;
const ACCESS_EXPIRY = (60 * 10) //seconds;

const MSG_FORM_INVALID = "Fields are incomplete or invalid";

module.exports = {
	MY_SQL_HOST,
	MY_SQL_USERNAME,
	MY_SQL_PASSWORD,
	DATABASE_NAME,
	USERS_TABLE,
	USERS_TABLE_COLUMNS,
	CHAT_TABLE,
	CHAT_TABLE_COLUMNS,
	CLOUDINARY_CONNECTION,
	UPLOAD_PATH,
	IMAGE_FILTER,
	PASSWORD_LENGTH,
	ACCESS_EXPIRY,
	MSG_FORM_INVALID
}