
//DATABASE CONSTANTS
const MY_SQL_HOST ='localhost';
const MY_SQL_USERNAME = 'kr34t1v';
const MY_SQL_PASSWORD = 'Papenvleis1!';
const DATABASE_NAME = 'matcha';
const USERS_TABLE = `${DATABASE_NAME}.Users`;
const USERS_TABLE_COLUMNS = `
Id INT AUTO_INCREMENT PRIMARY KEY,
AccessToken NVARCHAR(255),
Username NVARCHAR(255) NOT NULL,
Firstname NVARCHAR(255) NOT NULL,
Lastname NVARCHAR(255) NOT NULL,
Birthdate DATE NOT NULL,
Gender NVARCHAR(255) NOT NULL,
SexualPreference NVARCHAR(255) NOT NULL,
Email NVARCHAR(255),
NewEmail NVARCHAR(255),
DateVerified DATE,
VerifyKey NVARCHAR(255),
Password NVARCHAR(255) NOT NULL,
Biography NVARCHAR(255),
Interests JSON,
Location JSON,
Avatar NVARCHAR(255),
Images JSON,
BlockedUsers JSON,
ViewedBy JSON,
LikedBy JSON,
Liked JSON,
DateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DateModified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DateDeleted DATE
`;

//SECURITY REQUIREMENTS
const PASSWORD_LENGTH = 8;
const ACCESS_EXPIRY_TIME = 

module.exports = {
	MY_SQL_HOST,
	MY_SQL_USERNAME,
	MY_SQL_PASSWORD,
	DATABASE_NAME,
	USERS_TABLE,
	USERS_TABLE_COLUMNS,
	PASSWORD_LENGTH
}